services:
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./.config/tempo.yaml:/etc/tempo.yaml
      - ./tmp/tempo:/tmp/tempo
  #    ports:
  #      - "14268:14268" # jaeger ui
  #      - "3200:3200"   # tempo      
  #      - "4317:4317"  # otlp grpc
  #      - "4318:4318"  # otlp http